### PR TITLE
Made the importer tool use async downloading (not waiting on other downloads to finish)

### PR DESCRIPTION
**Pull request by Measurity**
Changed: Download of details to use async code so that downloads aren't waiting on eachother but can be started all at once.
Changed: Download of details doesn't block the UI thread anymore.

Please test my changes and comment on them!

### CODE REVIEW

**Comment by danielbarla** [comment]
Thanks for that - it's looking good at first glance.  I'll try to test it shortly and merge.

**Comment by danielbarla** [comment]
Had a chance to test, everything seems to be working, so I'll merge it in now.  Some general comments:
- Love the $string interpolation syntax in C#6.
- The #pragma statements to suppress await warnings is a bit odd for me (though obviously still better than leaving the warnings hanging).  Since await / task tends to spread through a project once you start using them, I suspect there will be quite a few cases where you simply want to "fire and forget", without making duplicate methods or mystical workarounds (such as var x = ...).  I'm not really looking to change it here, but what's your opinion on a Task extension method like Forget(), as shown in[ this SO post](http://stackoverflow.com/a/22630057)?  Apparently that kind of thing is a part of some internal VisualStudio libraries, so at least someone in MS seems to think it's an OK idea.
- Looking at a lot of the Import utility code specifically, I think I need to name a few things a bit more self-descriptively, and perhaps add a few comments here and there.  Going to look at that after I add some high level comments to the main app.

**Comment by Measurity** [comment]
Thank you for the approval. 

Glad you allow $string interpolation. Really like that feature as well.

I agree that #pragma is a bit verbose for what might look like a code-smell. Going with .Forget is more concise. If I have something new to add I'll check that SO post and apply it if it isn't changed before that.

Atm I also think that the utility code could be better named/placed. Maybe place all extension classes in a separate namespace 'Extensions'? Not the best solution but imo there aren't that many utility classes to bother with a hierarchical structure because it will likely change soon and having one class file per namespace is overdone. [Google: c# naming convention extension methods](https://www.google.nl/search?q=c%23+naming+convention+extension+methods&oq=C%23+naming+conventions+extension&aqs=chrome.1.69i57j0.9709j0j4&sourceid=chrome&ie=UTF-8)  gives me mixed naming convention preferences. I think I should have named my Controls extensions class 'ControlExtensions' then.

**Comment by danielbarla** [comment]
Hmm, I've generally avoided extension methods in shared code environments because unless you know about them somehow, people tend to be confused or reinvent them, etc.  As far as I know, VS is not clever enough to pull in hypothetical extensions in your project which have not yet been pulled in via a using declaration, and this tends to confuse people quite a bit.  E.g. when you're missing the `using System.Linq;` declaration, and can't figure out why you can't use LINQ features on collections - probably happened to all of us when LINQ was introduced.  But how are you supposed to know about extensions your teammates come up with?

So really, some kind of well known convention is probably the way to go, whether its a high-level Extensions namespace, or suffixing all the classes with 'Extensions' (though the latter does seem to be somewhat of an emerging standard I guess).  I suspect that for a project of this small size though, we shouldn't be overthinking it - though I do enjoying finding out about best practices, etc.

**Comment by Measurity** [comment]
I think I found a 'neater' solution to the .Forget(). Using .ConfigureAwait(true) is the same as not having anything behind the task but removed the ugly warning from the output.

.ConfigureAwait(false) is more performant but if you want to change UI elements after an async action then you need to invoke it (is slower).

**Comment by danielbarla** [comment]
Interesting, thanks for the update.

**Pull request merged**
